version: '2'
services:
  web:
    image: lumirang_odoo_enterprise_local
    build: .
    depends_on:
      - mydb
    ports:
      - "8079:8069"
    volumes:
    - ./addons:/mnt/extra-addons
    - ./conf/odoo_local.conf:/etc/odoo/odoo.conf
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    env_file:
      - ./conf/variables.env
  mydb:
    ports:
    - "5433:5432"
    image: postgres:10
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_DB=postgres