version: '2'
services:
  web:
    image: lumirang_odoo_enterprise_local
    build: .
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    volumes:
    - ./marfa:/mnt/extra-addons
    - ./enterprise:/mnt/enterprise
    - ./conf/odoo_local.conf:/etc/odoo/odoo.conf
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    ports:
    - "5432:5432"
    image: postgres:10
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_DB=postgres