version: '2'
services:
  web-test:
    build: .
    depends_on:
      - mydb-test
    ports:
      - "8069:8069"
    volumes:
      - ../../addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb-test:
    ports:
      - "5432:5432"
    image: postgres:10
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=myodoo
    - POSTGRES_DB=postgres