version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ./host.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ssl-certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - proxy-companion:/usr/share/nginx/html
      - ../../nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ssl-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
  web-worker:
    image: web-worker
    volumes:
      - ../../var/log:/var/log/nginx
    build: ./nginx
    depends_on:
      - odoo
    env_file:
      - ./variables.env
  odoo:
    image: lumirang-odoo
    build: .
    volumes:
      - /var/www/odoo-data:/var/lib/odoo
      - ../../addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    env_file:
      - ./credentials.env
volumes:
  ssl-certs:
  proxy-companion:

